#!/usr/bin/env ruby

require 'optparse'

options = {}
OptionParser.new do |opt|
  opt.on("-u", "--update-only", "Only updates MacPorts, doesn't clean anything") { options[:update_only] = true }
  opt.on("-c", "--cleanup", "Cleans old program versions and such") { |o| options[:cleanup] = true }
end.parse!

if options[:update_only]
  system "sudo port selfupdate"
  system "sudo port upgrade outdated"
elsif options[:cleanup]
  system "sudo port uninstall leaves"
  system "sudo port -N reclaim"
else
  system "sudo port selfupdate"
  system "sudo port upgrade outdated"
  system "sudo port uninstall leaves"
  system "sudo port -N reclaim"
end
